//
// Created by illidansr on 22.03.2021.
//

#ifndef SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_B_INCLUDE_LIB_B_HPP_
#define SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_B_INCLUDE_LIB_B_HPP_

#endif //SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_B_INCLUDE_LIB_B_HPP_
