//
// Created by illidansr on 22.03.2021.
//

#ifndef SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_D_INCLUDE_LIB_D_HPP_
#define SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_D_INCLUDE_LIB_D_HPP_

void hello_lib_d();
#endif //SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_D_INCLUDE_LIB_D_HPP_
