//
// Created by illidansr on 22.03.2021.
//

#ifndef SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_C_INCLUDE_LIB_C_HPP_
#define SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_C_INCLUDE_LIB_C_HPP_

#include "lib_d.hpp"

void hello_lib_c();

#endif //SUBPROJECT_TEST_SRC_BUISNESLAYER_LIB_C_INCLUDE_LIB_C_HPP_
