//
// Created by illidansr on 22.03.2021.
//

#ifndef SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_A_INCLUDE_LIB_A_HPP_
#define SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_A_INCLUDE_LIB_A_HPP_

int foo() {
    std::cout << "Hello" << std::endl;
}

#endif //SUBPROJECT_TEST_SRC_APPLICATIONLAYER_LIB_A_INCLUDE_LIB_A_HPP_
